networks:
  database:

volumes:
  mysql:

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    networks:
      - database
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=remix
      - MYSQL_PASSWORD=test
      - MYSQL_DB=remixtodos
    volumes:
      - mysql:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    networks:
      database:
        aliases:
          - mysql
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 1s
      retries: 120